export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const MY_POST_LIST_REQUEST = 'MY_POST_LIST_REQUEST';
export const MY_POST_LIST_SUCCESS = 'MY_POST_LIST_SUCCESS';
export const MY_POST_LIST_FAIL = 'MY_POST_LIST_FAIL';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const SINGLE_POST_VIEW_REQUEST = 'SINGLE_POST_VIEW_REQUEST';
export const SINGLE_POST_VIEW_SUCCESS = 'SINGLE_POST_VIEW_SUCCESS';
export const SINGLE_POST_VIEW_FAIL = 'SINGLE_POST_VIEW_FAIL';

export const POST_COMMENT_CREATE_REQUEST = 'POST_COMMENT_CREATE_REQUEST';
export const POST_COMMENT_CREATE_SUCCESS = 'POST_COMMENT_CREATE_SUCCESS';
export const POST_COMMENT_CREATE_FAIL = 'POST_COMMENT_CREATE_FAIL';
export const POST_COMMENT_CREATE_RESET = 'POST_COMMENT_CREATE_RESET';

export const POST_COMMENT_DELETE_REQUEST = 'POST_COMMENT_DELETE_REQUEST';
export const POST_COMMENT_DELETE_SUCCESS = 'POST_COMMENT_DELETE_SUCCESS';
export const POST_COMMENT_DELETE_FAIL = 'POST_COMMENT_DELETE_FAIL';

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_FAIL = 'POST_LIKE_FAIL';

export const POST_DISLIKE_REQUEST = 'POST_DISLIKE_REQUEST';
export const POST_DISLIKE_SUCCESS = 'POST_DISLIKE_SUCCESS';
export const POST_DISLIKE_FAIL = 'POST_DISLIKE_FAIL';
